# Generated by Django 3.2 on 2021-08-02 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_subscribe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribe',
            new_name='Subscriber',
        ),
    ]
